service:
  name: cassie

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  get:
    handler: src/handler.get
    events:
      - http:
          path: /cassie/
          method: get
      - http:
          path: /cassie/{path+}
          method: get
