service:
  name: cassie

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10

functions:
  get:
    handler: src/handler.get
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{path+}
          method: get

custom:
  customDomain:
    domainName: api.firebox.mkoelle.com
    basePath: 'cassie'
    stage: ${self:provider.stage}
    createRoute53Record: true
